package net.codejava;

import java.io.Serializable;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName = "Players")
public class Player implements Serializable{
	private static final long serialVersionUID = 1L;
    private String playerId;
    private String playerName;
    private Long timeToFinish;
    
    @DynamoDBHashKey(attributeName = "playerId")
    @DynamoDBAutoGeneratedKey
    public String getPlayerId() {
        return playerId;
    }
    
    @DynamoDBAttribute(attributeName = "playerName")
    public String getPlayerName() {
        return playerName;
    }
    
    @DynamoDBAttribute(attributeName = "timeToFinish")
    public Long getTimeToFinish() {
        return timeToFinish;
    }
    
    
    // setters
    public void setPlayerId(String playerId) {
        this.playerId = playerId;
    }
    
    public void setPlayerName(String playerName) {
        this.playerName = playerName;
    }
    
    public void setTimeToFinish(Long timeToFinish) {
        this.timeToFinish = timeToFinish;
    }
    
}
